// update the component versions for each release
:fuse-version: 7.5
:3scale-version: 2.7

// URLs
:openshift-console-url: {openshift-host}/dashboards
:route: https://wt4-{user-username}-3scale.{openshift-app-host}

//attributes
:title: 4 - Protecting APIs using 3scale API Management Platform
:3scale-name: Red Hat 3scale API Management Platform
:sample-api-key: testkey
:standard-fail-text: Verify that you followed all the steps. If you continue to have issues, contact your administrator.

//id syntax is used here for the custom IDs because that is how the Solution Explorer sorts these within groups
[id='4-protecting-apis']
= {title}

// word count that fits best is 15-22, with 20 really being the sweet spot. Character count for that space would be 100-125
Learn how to import an API into Red Hat 3scale API Management Platform and secure it using API Key security.

[type=walkthroughResource,serviceName=openshift]
.Red Hat OpenShift
****
* link:{openshift-console-url}[Console, window="_blank"]
* link:https://docs.openshift.com/dedicated/4/welcome/index.html/[OpenShift Documentation, window="_blank"]
* link:https://blog.openshift.com/[OpenShift Blog, window="_blank"]
****

[type=walkthroughResource,serviceName=fuse-managed]
.Red Hat Fuse Online
****
* link:{fuse-url}[Console, window="_blank", id="resources-fuse-url"]
* link:{fuse-documentation-url}[Fuse Documentation, window="_blank"]
****

[type=walkthroughResource,serviceName=3scale]
.Red Hat 3scale API Management Platform
****
* link:{api-management-url}[Console, window="_blank"]
* link:https://developers.redhat.com/products/3scale/overview/[3Scale Overview, window="_blank"]
* link:https://www.3scale.net[3Scale Website, window="_blank"]
****

:sectnums:

[time=10]
== Importing an API to 3scale using Service Discovery
:context: import-api
=== API Management Login

. Open the link:{api-management-url}[{3scale-name} Login screen, window="_blank", id="{context}-1"].

. Select the *Authenticate through Red Hat Single Sign-On* option. This triggers an OAuth Flow and redirects you to the {3scale-name} Dashboard.

. Dismiss the *How does 3Scale work?* option which is displayed the first time you log in to {3scale-name}. The main Dashboard is displayed.

[type=verification]
Can you see the {3scale-name} Dashboard that shows the Audience and APIs panels?

[type=verificationFail]
{standard-fail-text}


=== Import the API to Red Hat 3scale

Follow these steps to import the API to 3scale. Since Fuse Online automatically added 3scale discovery annotations to the Greeting API it can be imported using the link:https://access.redhat.com/documentation/en-us/red_hat_3scale_api_management/2.7/html/admin_portal_guide/service-discovery[Service Discovery, window="_blank"] features of 3scale.

. From the *APIs* section of the *Dashboard*, select the *New Product* item.
+
NOTE: Ask an administrator to grant you the necessary 3scale permission if *New Product* is not displayed.

. Select the *Import from OpenShift* option. If this option is not enabled, click the *Authenticate to enable this option* link and choose *Allow selected permissions*.
. If you used the *Authenticate to enable this option* link, verify that you have reselected *Import from OpenShift* after being redirected.
. In the SERVICE section:
.. Verify the *Namespace* field has *redhat-rhmi-fuse* selected.
.. Verify the *Name* field has *i-greeting-integration-{user-username}* selected.
. Click *Create Product*.
+
NOTE: The import process may take a few minutes to complete.

[type=verification]
Look at the *APIs* section of the 3scale Dashboard and make sure the *PRODUCTS* tab is active. Can you see the *i-greeting-integration-{user-username} API* listed there?

[type=verificationFail]
Wait a little longer, or try the import again. {standard-fail-text}

[time=10]
== Configuring the API in 3scale API Management

=== Set the Staging Environment API URL
. Go to the link:{api-management-url}[{3scale-name} 3scale Dashboard, window="_blank"]. Log in if necessary.
. Choose *i-greeting-integration-{user-username}* from the top navigation menu to view the {3scale-name} homepage.
+
NOTE: If the *i-greeting-integration-{user-username}* is not listed in the top navigation menu that means it is still being imported. Wait a while, refresh the page, and try again.

. Select *Integration > Settings* from the vertical navigation menu on the left.
+
Note: You may see a warning icon next to Integration > Configuration. We'll address this warning shortly.

. In the DEPLOYMENT > API GATEWAY section of the *Settings* page, change the *Staging Public Base URL* field to:
+
[subs="attributes+"]
----
{route}
----
+
NOTE: We change the URL because the default one generated is usually too long and will fail to resolve.

. Scroll down and click *Update Product* at the bottom of the page.

=== Create a Mapping Rule for the Greeting Endpoint

. Select *Integration > Mapping Rules* from the vertical navigation menu on the left.
. Delete the default *GET /* mapping by clicking the red trash can icon beside it.
. Click *Add Mapping Rule*.
. On the *New Mapping Rule* screen:
.. In the *Verb* field, select *POST*.
.. For the *Pattern*, enter `/greeting`.
.. Skip the other fields and click *Create Mapping Rule*.
. Select *Integration > Configuration* from the vertical navigation menu on the left.
. In the *APIcast Configuration* section on the *Configuration* screen, click *Promote v.2 to Staging*.

[type=verification]
Look at the *Integration > Configuration* screen and find the *Environments* section. Is the staging environment information *URL* value of {route}?

[type=verificationFail]
{standard-fail-text}

[time=10]
== Creating an Application and Application Plan

Note that the *Example curl for testing* listed for the *Staging Environment* in *Integration > Configuration* contains a placeholder API Key in the *user_key* querystring parameter. To obtain a valid API Key that enables a client to consume the API, the API must be added as an *Application* within a developer account. This *Application* must be part of an *Application Plan*. An *Application Plan* is used to define pricing, limits, methods, and metrics.


=== Create an Application Plan

. Go to the link:{api-management-url}[{3scale-name} 3scale Dashboard, window="_blank"]. Log in if necessary.
. Choose *i-greeting-integration-{user-username}* from the top navigation menu to view the {3scale-name} homepage.
. Select *Applications > Application Plans* the vertical navigation menu on the left.
. Select *Create Application Plan*.
. On the *Create Application Plan* screen:
.. In both the *Name* and *System name* fields, enter:
+
[subs="attributes+"]
----
low-code-{user-username}
----
.. Leave the other fields with their default values.
.. Select *Create Application Plan*.
. You will be redirected to the *Application Plans* screen.
. Look for the item named *low-code-{user-username}* in the list and click *Publish*. The State will change to "published".

=== Create an Application
In this step a new *Application* will be created for the *Developer* Group,  assigned to the *Application Plan* created in the previous section.

. In 3scale, select *Audience* from the top navigation menu.
. Select the *Developer* Account to open the *Account Summary* page.
. Select the *(num) Application* item from the breadcrumb (below the top navigation menu) to view the developer's Applications.
. Click the *Create Application* button in the top right.
. On the *New Application* screen:
.. Verify the *Application plan* field is set to *low-code-{user-username}* under the *i-greeting-integration-{user-username}* grouping.
.. Verify the *Service plan* field is set to *Default*.
..  For both the *Name* and *Description* fields, enter:
+
[subs="attributes+"]
----
low-code-app-{user-username}
----
.. Click *Create Application*.

. Set a custom *User Key* for the application:
.. On the *low-code-app-{user-username}* Application screen you were redirected to, look for the *API Credentials* section.
.. Click the green pencil icon beside the *User Key*
.. In the *Set Custom User Key* modal dialog, enter:
+
[subs="attributes+"]
----
{sample-api-key}
----
.. Click *Set Custom Key*.


[type=verification]
Return to the *Integration > Configuration* screen. Does the *Example curl for testing* under the *Staging Environment* show `user_key={sample-api-key}`?

[type=verificationFail]
{standard-fail-text}


[time=5]
== Invoking the API

. Use an HTTP client such as cURL or Postman to invoke the `POST /greeting` route. For example, you can use cURL like so:
+
[subs="attributes+"]
----
curl -d '{"name":"OpenShift"}' \
-H "Content-Type: application/json" \
-X POST "{route}/greeting?user_key={sample-api-key}"
----

[type=verification]
Did the message `Hello from, OpenShift` appear in your Slack channel?

[type=verificationFail]
{standard-fail-text}
